// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PulseConnectServer.Utilities.DatabaseContexts;

#nullable disable

namespace PulseConnectServer.Migrations
{
    [DbContext(typeof(IntegratedServerUsersDBContext))]
    [Migration("20260311213031_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Users")
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PulseConnectLib.Definitions.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CurrentSessionID")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("SessionExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("TimeUserCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TypeOfUser")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AllServerUsers", "Users");

                    b.HasDiscriminator<string>("TypeOfUser").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PulseConnectLib.Definitions.Entities.DoctorUser", b =>
                {
                    b.HasBaseType("PulseConnectLib.Definitions.Entities.User");

                    b.Property<bool>("CanStartRapidResponse")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanTransferShift")
                        .HasColumnType("tinyint(1)");

                    b.PrimitiveCollection<string>("GroupGUIDs")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsCurrentlyOnShift")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ReceiveRapidResponseAlert")
                        .HasColumnType("tinyint(1)");

                    b.HasDiscriminator().HasValue("DocUser");
                });

            modelBuilder.Entity("PulseConnectLib.Definitions.Entities.NurseUser", b =>
                {
                    b.HasBaseType("PulseConnectLib.Definitions.Entities.User");

                    b.Property<string>("WardId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue("NurseUser");
                });
#pragma warning restore 612, 618
        }
    }
}
