// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PulseConnectServer.Utilities.DatabaseContexts;

#nullable disable

namespace PulseConnectServer.Migrations.StandAloneRRTEventsDB
{
    [DbContext(typeof(StandAloneRRTEventsDBContext))]
    [Migration("20260315221009_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PulseConnectLib.Definitions.Events.RapidResponseEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EventCallerGuid")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EventClass")
                        .HasColumnType("int");

                    b.Property<string>("EventData")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EventGuid")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EventSeverity")
                        .HasColumnType("int");

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PatientCurrentLocationGuid")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PatientGuid")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RRTEventType")
                        .HasColumnType("int");

                    b.Property<bool>("RoscAchieved")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("TimeToRosc")
                        .HasColumnType("int");

                    b.ComplexProperty<Dictionary<string, object>>("PatientLocation", "PulseConnectLib.Definitions.Events.RapidResponseEvent.PatientLocation#WardBed", b1 =>
                        {
                            b1.Property<string>("BedNumber")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("PatientLocationBedNumber");

                            b1.Property<string>("WardName")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("PatientLocationWardName");
                        });

                    b.HasKey("Id");

                    b.ToTable("ListOfStandaloneEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
